### ISSUE TITLE
RTL issue

### ISSUE THREAD

**Issue by Mister--H** [themeum/tutorstarter#1]
rtl.css:104 

```
.elementor-widget-container, .elementor-widget-container p {
    **text-align: right !important;**
    padding-right: 15px;
}
```

it's shouldn't be !important, somewhere we need to change the text align (with elementor) but cuz of this we cant

**Comment by Mister--H** [comment]
actually you should remove the text-align: right from this block of code

**Comment by zamanq** [comment]
@Mister--H 
Thank you for pointing out the issue. We'll verify it and make changes in the next update if it's the actual reason for alignment issue.

**Comment by Mister--H** [comment]
yea, i removed it and everything is good, there is one more issue the eicons in rtl are upside down, i rotate it 180deg
